# Project: TSA3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o glew.o
LINKOBJ  = main.o glew.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/Users/Mark/OneDrive/Documents/2T_SY21-22/Computer Graphics and Visual Computing/Works/freeglut/lib/x64" -L"C:/Users/Mark/OneDrive/Documents/2T_SY21-22/Computer Graphics and Visual Computing/Works/glew-2.1.0/lib/Release/x64" -lopengl32 -lfreeglut -lglu32 -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Mark/OneDrive/Documents/2T_SY21-22/Computer Graphics and Visual Computing/Works/freeglut/include" -I"C:/Users/Mark/OneDrive/Documents/2T_SY21-22/Computer Graphics and Visual Computing/Works/glew-2.1.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/Mark/OneDrive/Documents/2T_SY21-22/Computer Graphics and Visual Computing/Works/freeglut/include" -I"C:/Users/Mark/OneDrive/Documents/2T_SY21-22/Computer Graphics and Visual Computing/Works/glew-2.1.0/include"
BIN      = TSA3.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

glew.o: glew.c
	$(CPP) -c glew.c -o glew.o $(CXXFLAGS)
